# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Production Build and deploy container app to Azure Web App - klinicx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://prattle.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_dccd258303fd464591bebe29f0f25829 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6285cd76948d4fe687131011e4d7b2e9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: prattle.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dccd258303fd464591bebe29f0f25829 }}/klinicx-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'klinicx'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dc3cee0df67342bbbdb119fa6a296320 }}
        images: 'prattle.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_dccd258303fd464591bebe29f0f25829 }}/klinicx-app:${{ github.sha }}'
